baseURL = "https://www.fukuball.com/hugo/"
languageCode = "en-us"
title = "Fukuball"
disqusShortname = 'fukuball'

[Author]
  name = "Fukuball Link"
  email = "fukuball@gmail.com"
  facebook = "fukuball"
  github = "fukuball"
  twitter = "fukuball"
  instagram = "fukuball"

[[menu.main]]
    name = "About"
    url = "about"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
